[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Read-NonEmptyInput {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Prompt
    )

    while ($true) {
        $value = Read-Host $Prompt
        if (-not [string]::IsNullOrWhiteSpace($value)) {
            return $value.Trim()
        }
        Write-Host "Value cannot be empty. Please try again." -ForegroundColor Yellow
    }
}

function Read-PositiveInteger {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Prompt
    )

    while ($true) {
        $inputValue = Read-Host $Prompt
        $number = 0
        if ([int]::TryParse($inputValue, [ref]$number) -and $number -gt 0) {
            return $number
        }
        Write-Host "Please enter a positive whole number." -ForegroundColor Yellow
    }
}

function Read-Mode {
    while ($true) {
        $modeInput = Read-Host "Mode (RIM / LH / BOTH)"
        if ([string]::IsNullOrWhiteSpace($modeInput)) {
            Write-Host "Mode cannot be empty. Please enter RIM, LH, or BOTH." -ForegroundColor Yellow
            continue
        }

        $mode = $modeInput.Trim().ToUpperInvariant()
        if ($mode -in @('RIM', 'LH', 'BOTH')) {
            return $mode
        }

        Write-Host "Invalid mode. Allowed values: RIM, LH, BOTH." -ForegroundColor Yellow
    }
}

function New-Utf8File {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,
        [Parameter(Mandatory = $true)]
        [string]$Content
    )

    $directory = Split-Path -Path $Path -Parent
    if (-not (Test-Path -LiteralPath $directory)) {
        New-Item -ItemType Directory -Path $directory -Force | Out-Null
    }

    [System.IO.File]::WriteAllText($Path, $Content, [System.Text.UTF8Encoding]::new($false))
}

function Get-SafeFolderSegment {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Value
    )

    $trimmed = $Value.Trim()
    $invalidChars = [System.IO.Path]::GetInvalidFileNameChars()
    foreach ($char in $invalidChars) {
        $trimmed = $trimmed.Replace([string]$char, '_')
    }

    $normalized = ($trimmed -replace '\s+', '_').ToUpperInvariant()
    return $normalized
}

$ictoNumber = Read-NonEmptyInput -Prompt 'ICTO number'
$applicationName = Read-NonEmptyInput -Prompt 'Application name'
$mode = Read-Mode
$region = Read-NonEmptyInput -Prompt 'Region'
$schemaCount = Read-PositiveInteger -Prompt 'Number of schemas'

$schemas = @()
for ($index = 1; $index -le $schemaCount; $index++) {
    Write-Host "\nSchema mapping #$index" -ForegroundColor Cyan
    $sourceSchema = Read-NonEmptyInput -Prompt '  Source Sybase schema'
    $targetSchema = Read-NonEmptyInput -Prompt '  Target SQL Server schema'

    $schemas += [PSCustomObject]@{
        Source = $sourceSchema
        Target = $targetSchema
    }
}

$baseFolderName = "{0}_{1}" -f (Get-SafeFolderSegment -Value $ictoNumber), (Get-SafeFolderSegment -Value $applicationName)
$baseFolderPath = Join-Path -Path (Get-Location) -ChildPath $baseFolderName

if (Test-Path -LiteralPath $baseFolderPath) {
    throw "Output folder '$baseFolderPath' already exists. Choose a different ICTO/application combination or remove the existing folder."
}

$ddlgenPath = Join-Path -Path $baseFolderPath -ChildPath 'ddlgen'
$loaderPath = Join-Path -Path $baseFolderPath -ChildPath 'loader'
$scriptsPath = Join-Path -Path $baseFolderPath -ChildPath 'scripts'
$rfcPath = Join-Path -Path $baseFolderPath -ChildPath 'rfc'
$rfcSqlOutputPath = Join-Path -Path $rfcPath -ChildPath 'sql_output'

New-Item -ItemType Directory -Path $ddlgenPath, $loaderPath, $scriptsPath, $rfcPath, $rfcSqlOutputPath -Force | Out-Null

for ($index = 0; $index -lt $schemas.Count; $index++) {
    $schema = $schemas[$index]
    $schemaFolderName = '{0:D2}_{1}_TO_{2}' -f ($index + 1), (Get-SafeFolderSegment -Value $schema.Source), (Get-SafeFolderSegment -Value $schema.Target)
    $schemaFolderPath = Join-Path -Path $ddlgenPath -ChildPath $schemaFolderName
    $ymlPath = Join-Path -Path $schemaFolderPath -ChildPath 'application_mssql.yml'

    $ymlContent = @"
# SQL Server ddlgen configuration
# Generated by generate_mssql_migration_pack.ps1

migration:
  icto_number: "$ictoNumber"
  application: "$applicationName"
  mode: "$mode"
  region: "$region"

schema:
  source_sybase: "$($schema.Source)"
  target_mssql: "$($schema.Target)"

# TODO: add any environment-specific parameters required by your ddl generator.
"@

    New-Utf8File -Path $ymlPath -Content $ymlContent
}

$loaderConfigPath = Join-Path -Path $loaderPath -ChildPath 'loader_config_template.yml'
$schemaMappings = ($schemas | ForEach-Object {
@"
  - source_sybase: "$($_.Source)"
    target_mssql: "$($_.Target)"
"@
}) -join "`n"

$loaderContent = @"
# Loader configuration template
# Update placeholders before execution on Linux.

global:
  icto_number: "$ictoNumber"
  application: "$applicationName"
  mode: "$mode"
  region: "$region"
  source_server: "<source_sybase_server>"
  target_server: "<target_mssql_server>"
  batch_size: 10000

schemas:
$schemaMappings
# TODO:
# - fill in credentials handling strategy
# - adjust loader tuning parameters
"@
New-Utf8File -Path $loaderConfigPath -Content $loaderContent

$runMigrationPath = Join-Path -Path $scriptsPath -ChildPath 'run_migration.sh'
$runMigrationContent = @'
#!/usr/bin/env bash
set -euo pipefail

# Executes SQL Server DDL generation for each schema config.
# Run from the root of this migration pack on Linux.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PACK_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DDLGEN_DIR="$PACK_ROOT/ddlgen"

if [[ ! -d "$DDLGEN_DIR" ]]; then
  echo "ddlgen directory not found at $DDLGEN_DIR" >&2
  exit 1
fi

echo "Starting SQL Server DDL generation..."

while IFS= read -r -d '' cfg; do
  cfg_dir="$(dirname "$cfg")"
  echo "Running in: $cfg_dir"
  (
    cd "$cfg_dir"
    ./ddl_gen.sh mssql
  )
done < <(find "$DDLGEN_DIR" -type f -name 'application_mssql.yml' -print0)

echo "Done. Copy resulting SQL artifacts into rfc/sql_output/."
'@
New-Utf8File -Path $runMigrationPath -Content $runMigrationContent

$instructionsPath = Join-Path -Path $rfcPath -ChildPath 'Instructions.txt'
$schemaInstructions = ($schemas | ForEach-Object { "- Source: $($_.Source) -> Target: $($_.Target)" }) -join [Environment]::NewLine

$instructionsContent = @"
Migration Pack Instructions
===========================

ICTO Number : $ictoNumber
Application : $applicationName
Mode        : $mode
Region      : $region

Schema mappings:
$schemaInstructions

Steps:
1. Copy this entire folder to the target Linux migration server.
2. Ensure ddl_gen.sh is present and executable in each ddlgen schema folder.
3. From scripts/, run: ./run_migration.sh
4. Review generated SQL outputs.
5. Place approved SQL files into rfc/sql_output/ for RFC packaging.
6. Update this file with environment-specific notes and approvals.
"@
New-Utf8File -Path $instructionsPath -Content $instructionsContent

$placeholderPath = Join-Path -Path $rfcSqlOutputPath -ChildPath '.keep'
New-Utf8File -Path $placeholderPath -Content "Placeholder file to keep sql_output folder in source control.`n"

Write-Host "`nMigration pack generated successfully:" -ForegroundColor Green
Write-Host "  $baseFolderPath"
"Schema configurations created: $($schemas.Count)" | Write-Host
